### ISSUE TITLE
Log in but taken back to homepage without login

### ISSUE THREAD

**Issue by shenyp09** [indico/indico#1732]
version: indico 1.1.2

Sometimes I find that I log in but then I'm take back to homepage without login. The cookie of browser was open. If I clear the cookie of indico left in my browser, I can log in successfully again.

What can I do to solve this problem?

**Comment by pferreir** [comment]
Maybe a cache problem? The web session should be stored in the session cache.
Or are you by any chance enabling the "cache" option in the general settings? I believe versions < 1.2 included that option, which is now known to cause over-caching.

**Comment by shenyp09** [comment]
I have disabled the cache option in general settings, but the problem is not solved.

I'm trying to update to version 1.2 now, but not success yet.

**Comment by pferreir** [comment]
Are you seeing any errors in `indico.log`?

**Comment by shenyp09** [comment]
There is nothing.

**Comment by pferreir** [comment]
Do you mean that there are no errors or that the file is empty?

**Comment by shenyp09** [comment]
In fact, there are some errors in log file, but none of them seems related to this problem. I will take a look again.


来自 魅族 MX2

-------- 原始邮件 --------
发件人：Pedro Ferreira <notifications@github.com>
时间：周二 1月20日 00:33
收件人：indico/indico <indico@noreply.github.com>
抄送："Ryan F. Shen" <shenyp09@gmail.com>
主题：Re: [indico] Log in but taken back to homepage without login (#1732)

**Comment by pferreir** [comment]
If you could paste those, it would maybe help...

**Comment by shenyp09** [comment]
I have checked the indico.conf again. After the last restart of system. there is no any new log at all. But there is something in schedule.log. 

`schedule.log`
```
2015-01-21 15:06:08,254 18599 ZEO.ClientStorage: INFO     ('127.0.0.1', 9675) ClientStorage (pid=18599) created RW/normal for storage: '1'
2015-01-21 15:06:08,255 18599 ZEO.cache: INFO     created temporary cache file '<fdopen>'
2015-01-21 15:06:08,273 18599 ZEO.zrpc.Connection(C): INFO     (127.0.0.1:9675) received handshake 'Z3101'
2015-01-21 15:06:08,273 18599 ZEO.ClientStorage: INFO     ('127.0.0.1', 9675) Testing connection <ManagedClientConnection ('127.0.0.1', 9675)>
2015-01-21 15:06:08,274 18599 ZEO.ClientStorage: INFO     ('127.0.0.1', 9675) Server authentication protocol None
2015-01-21 15:06:08,274 18599 ZEO.ClientStorage: INFO     ('127.0.0.1', 9675) Connected to storage: ('localhost', 9675)
2015-01-21 15:06:08,275 18599 ZEO.ClientStorage: INFO     ('127.0.0.1', 9675) No verification necessary -- empty cache
```

And I find that `indico_schedule` cannot start or stop. Tasks in schedule cannot run anymore.

```
$ sudo -u www-data indico_scheduler stop
Waiting for death confirmation... 
FAILED!
DONE!
```

**Comment by pferreir** [comment]
Are you sure that the logging level in `logging.conf` is properly set? By default it is `UNSET` (something we should change).

**Comment by shenyp09** [comment]
Oh! I didn't set it. I will set it WARNING and paste the log here.

**Comment by shenyp09** [comment]
`indico.log`

```
2015-01-21 19:22:30,533 indico.requestHandler: WARNING  - Conflict in Database! (Request 2982181964)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/indico-1.1.2-py2.7.egg/MaKaC/webinterface/rh/base.py", line 598, in process
    DBMgr.getInstance().endRequest( True )
  File "/usr/local/lib/python2.7/dist-packages/indico-1.1.2-py2.7.egg/MaKaC/common/db.py", line 122, in endRequest
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/indico-1.1.2-py2.7.egg/MaKaC/common/db.py", line 146, in commit
    transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/transaction-1.4.3-py2.7.egg/transaction/_manager.py", line 111, in commit
    return self.get().commit()
  File "/usr/local/lib/python2.7/dist-packages/transaction-1.4.3-py2.7.egg/transaction/_transaction.py", line 280, in commit
    reraise(t, v, tb)
  File "/usr/local/lib/python2.7/dist-packages/transaction-1.4.3-py2.7.egg/transaction/_transaction.py", line 271, in commit
    self._commitResources()
  File "/usr/local/lib/python2.7/dist-packages/transaction-1.4.3-py2.7.egg/transaction/_transaction.py", line 417, in _commitResources
    reraise(t, v, tb)
  File "/usr/local/lib/python2.7/dist-packages/transaction-1.4.3-py2.7.egg/transaction/_transaction.py", line 391, in _commitResources
    rm.commit(self)
  File "/usr/local/lib/python2.7/dist-packages/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/Connection.py", line 567, in commit
    self._commit(transaction)
  File "/usr/local/lib/python2.7/dist-packages/ZODB3-3.10.5-py2.7-linux-i686.egg/ZODB/Connection.py", line 615, in _commit
    raise ConflictError(object=obj)
ConflictError: database conflict error (oid 0x0611, class MaKaC.webinterface.displayMgr.Menu)

2015-01-22 01:56:41,561 indico.requestHandler: ERROR    - Request 2986187020 failed: "'Calendar' object has no attribute 'set'"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/indico-1.1.2-py2.7.egg/MaKaC/webinterface/rh/base.py", line 586, in process
    res = self._process()
  File "/usr/local/lib/python2.7/dist-packages/indico-1.1.2-py2.7.egg/MaKaC/webinterface/rh/conferenceDisplay.py", line 1054, in _process
    data = serializer(resultFossil)
  File "/usr/local/lib/python2.7/dist-packages/indico-1.1.2-py2.7.egg/indico/web/http_api/metadata/serializer.py", line 64, in __call__
    self._data = self._execute(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/indico-1.1.2-py2.7.egg/indico/web/http_api/metadata/ical.py", line 157, in _execute
    cal.set('version', '2.0')
AttributeError: 'Calendar' object has no attribute 'set'
```

`zeo.log`

```
2015-01-21T22:39:28 (127.0.0.1:58873) received handshake 'Z3101'
2015-01-21T22:39:28 (unconnected) disconnected
2015-01-21T22:39:28 (unconnected) disconnected
2015-01-22T02:20:53 (127.0.0.1:58863) disconnected
2015-01-22T02:23:04 new connection ('127.0.0.1', 58880): <ManagedServerConnection ('127.0.0.1', 58880)>
2015-01-22T02:23:04 new connection ('127.0.0.1', 58881): <ManagedServerConnection ('127.0.0.1', 58881)>
2015-01-22T02:23:04 new connection ('127.0.0.1', 58882): <ManagedServerConnection ('127.0.0.1', 58882)>
2015-01-22T02:23:04 (127.0.0.1:58880) received handshake 'Z3101'
2015-01-22T02:23:04 (unconnected) disconnected
2015-01-22T02:23:04 (unconnected) disconnected
2015-01-22T03:00:02 (127.0.0.1:58873) disconnected
2015-01-22T03:09:47 new connection ('127.0.0.1', 58883): <ManagedServerConnection ('127.0.0.1', 58883)>
2015-01-22T03:09:47 new connection ('127.0.0.1', 58884): <ManagedServerConnection ('127.0.0.1', 58884)>
2015-01-22T03:09:47 new connection ('127.0.0.1', 58885): <ManagedServerConnection ('127.0.0.1', 58885)>
2015-01-22T03:09:47 (127.0.0.1:58883) received handshake 'Z3101'
2015-01-22T03:09:47 (unconnected) disconnected
2015-01-22T03:09:47 (unconnected) disconnected
2015-01-22T08:34:44 (127.0.0.1:58880) disconnected
2015-01-22T08:39:12 new connection ('127.0.0.1', 58888): <ManagedServerConnection ('127.0.0.1', 58888)>
2015-01-22T08:39:12 new connection ('127.0.0.1', 58889): <ManagedServerConnection ('127.0.0.1', 58889)>
2015-01-22T08:39:12 new connection ('127.0.0.1', 58890): <ManagedServerConnection ('127.0.0.1', 58890)>
2015-01-22T08:39:12 (127.0.0.1:58888) received handshake 'Z3101'
2015-01-22T08:39:12 (unconnected) disconnected
2015-01-22T08:39:12 (unconnected) disconnected
2015-01-22T08:39:29 (127.0.0.1:58883) disconnected
2015-01-22T08:44:15 new connection ('127.0.0.1', 58891): <ManagedServerConnection ('127.0.0.1', 58891)>
2015-01-22T08:44:16 new connection ('127.0.0.1', 58892): <ManagedServerConnection ('127.0.0.1', 58892)>
2015-01-22T08:44:16 new connection ('127.0.0.1', 58893): <ManagedServerConnection ('127.0.0.1', 58893)>
2015-01-22T08:44:16 (127.0.0.1:58891) received handshake 'Z3101'
2015-01-22T08:44:16 (unconnected) disconnected
2015-01-22T08:44:16 (unconnected) disconnected
```

Other logs are clean.

**Comment by pferreir** [comment]
OK, first of all, you have the wrong version of the `icalendar` package installed. This is a problem with Indico 1.1, but it has been solved since. If you install version 3.2 (of `icalendar`) it should be OK. But this seems unrelated.
Can you try checking the cookies that you are getting from Indico, using your browser settings? This definitely looks like a web session issue.

**Comment by shenyp09** [comment]
The problem seems have been solved. It may be the problem of `icalendar` version.

**Comment by pferreir** [comment]
OK, then I will close the ticket. Don't hesitate to re-open if you notice anything else.

**Comment by shenyp09** [comment]
The problem seems still not solved. 

The problem won't happen on Chrome (version>40), but on other browsers the problem is still there. Recently I have received a lot of complain.

I think there must be some bug in the cookies of indico. Because the problem can be solved through deleting the recent cookies of browser.
